---
title: "Spatial patterns in Pinus pinea regeneration transects"
output:
  html_document: default
  html_notebook: default
  word_document: default
---
[output published (also) in: http://rpubs.com/scotti/SPA_PinusPinea_Tortoli]

# Recovering transects data
```{r access_data, echo=FALSE}
library(googlesheets)
suppressMessages(library(dplyr))
gst <-"TransectPinusPinea" 
gs_ls(gst)
tpp <- gs_title(gst)
wsn <- "PointPatternWithMarks"
cat("Sheet '", wsn, "'", ifelse(wsn %in% gs_ws_ls(tpp),"", "NOT "), "found.")
ppwm <- tpp %>% gs_read(ws=wsn)
ppwm$nPf <- as.factor(ppwm$`N palchi`)
str(ppwm)
```

# Initializing PPP and SO list
Spatial patterns windows are, partially, undefined. The width is fixed to 10m while the length is open and has to be estimated!!
```{r}
library(spatstat)
Areas <- unique(ppwm$Area)
t_windows <- list()
for(tid in Areas) t_windows[[tid]] <- ripras(ppwm$X[ppwm$Area==tid],ppwm$Y[ppwm$Area==tid], shape = "rectangle")
# ripras():  Estimate window from points alone
reduced <- c(1, 2, 3, 4, 6, 5, 7)
ppwm0 <- ppwm
ppwm <- ppwm[, reduced]
names(ppwm)[5:7] <- c("#whorls", "height [m]", "crown [m^2]")
trss <- solist()
# To display transects as seen from the see
#    exchange x and y
#    mirror on the negative side the y ==> K=-1
K <- -1
for(tid in Areas) {
  trs <- ppp(ppwm$Y[ppwm$Area==tid],K*c(ppwm$X[ppwm$Area==tid])
             , yrange = range(K*t_windows[[tid]]$xrange), xrange = c(-10, 10)
             , marks = ppwm[ppwm$Area==tid, c(5:7)])
  unitname(trs) <- "m"
#  print(paste(tid,class(trs)))
  trss[[length(trss)+1]] <- trs
}
names(trss)=paste("Trs-",Areas,sep="")
```


# Transects density distribution analysis
```{r}
plot(as.solist(lapply(trss, density)), nrows=1, equal.scales=T, valign=T, 
      main = "", hsep=2, cex.main=.7,
      equal.ribbon=TRUE, ribbon = T, ribside="left",
      panel.end=function(i,y,...){contour(y, ...)})
#      par(mar=c(0,0,2,0)), 
#  title(main="Density distribution", line =-1)
Axis(trss, side=4, cex.axis=.6, at=seq(100,20,-20), labels = seq(0,80,20), line = -3)
text(150,70,"distance [m]", srt = 90)
```


# Correlations among marks
```{r, warning=FALSE}
library("PerformanceAnalytics", lib.loc="~/R/win-library/3.3")
ow <- options("warn")[[1]]
options(warn = -1)
for(i in 1:4) chart.Correlation(marks(trss[[i]])
                                , histogram=TRUE, pch=19
                                , main=names(trss)[i])
options(warn = ow)

```


# Distribution of mark values
```{r}
for(i in 1:length(trss)) {
  tid <- names(trss)[i]
  trs <- trss[[tid]]
  plot(trs, cex.main=1.1, main="", 
       hsep=0, par(mar=c(0,0.5,0,0), cex=.6), mar.panel=c(0,0,0,.9))
  title(main = paste("Marks in",tid), line = -2)
}
#        which.marks = c(9, 1, 3), 
#        main.panel=c("#whorls", "height [m]", "crown [m^2]"), 

```


# Analysis of spatial characters
```{r}
Kl <- as.anylist(lapply(trss, Kest))
for(i in 1:length(Kl)) {
  leg <- plot(Kl[[i]], legend = F, main=names(Kl)[[i]])
  legend("topleft",legend = leg$key, lty=leg$lty, col=leg$col)
}
```


# Analysis of the spatial behaviour of each mark
```{r}
pmkc <- function(x, m) plot(main=paste(names(trss)[x],":"
                                ,names(trss[[1]]$marks)[m])
                     ,markcorr(setmarks(unmark(trss[[x]])
                                       ,marks(trss[[x]])[[m]])))

for(m in 1:length(marks(trs))) {
  for(i in 1:length(trss)) pmkc(i, m)
}


```


